namespace conncetASPwithTemplate.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class seedItems : DbMigration
    {
        public override void Up()
        {
            Sql(@"
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1204', N'Escalope', N'اسكالوب', N'', 0, 1, 0, 5, 0, 0, 0, 0, 0, NULL, N'-128', N'-16777216', 0, 0, 79, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:37:35', N'2019-07-05 19:11:31', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1205', N'Noodles With Meat& Nutes', N'شعرية بالحمة + المكسرات', N'', 0, 1, 0, 5, 0, 0, 0, 0, 0, NULL, N'-128', N'-16777216', 0, 0, 61, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:38:42', N'2019-07-05 19:11:43', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1206', N'Stuffed Pigeon', N'حمام محشى ( ارز او فريك )', N'', 0, 1, 0, 5, 0, 0, 0, 0, 0, NULL, N'-128', N'-16777216', 0, 0, 57, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:39:08', N'2019-07-05 19:11:54', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1207', N'Grilled Chicken With Mushroom or Pepper Souce		', N'صدر فراخ بصوص المشروم او الفلفل', N'', 0, 1, 0, 5, 0, 0, 0, 0, 0, NULL, N'-128', N'-16777216', 0, 0, 72, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:40:02', N'2019-07-05 19:12:04', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1208', N'Zucchini bechmalWith meat(ovenbaked)	', N'كوسه بالباشميل و اللحمة المفرومة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-128', N'-16777216', 0, 0, 26, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:40:31', N'2019-07-05 19:12:16', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1301', N'Smashed Potatoes ', N'بطاطس مهروسة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 15, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:42:54', N'2019-10-01 13:06:54', 8, 0, 0, 1, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1302', N'Boiled rice', N'ارز مسلوق', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 12, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:43:15', N'2019-10-01 13:07:22', 8, 0, 0, 1, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1303', N'Rice', N'ارز سادة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 11, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:43:37', N'2019-07-05 19:14:00', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1304', N'Rice & Nuts', N'ارز بالمكسرات', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 23, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:43:57', N'2019-07-05 19:14:08', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1305', N'Mixed Rice( Veal liver )', N'ارز بالخلطة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 21, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:44:23', N'2019-07-05 19:14:18', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1306', N'Noodels With Nuts', N'شعرية بالمكسرات', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323200', N'-16777216', 0, 0, 31, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 15:45:04', N'2019-07-05 19:14:29', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1401', N'Fattah (plain)', N'فتة سادة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-16711808', N'-16777216', 0, 0, 24, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:08:27', N'2018-07-12 17:18:26', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1402', N'Vegtables With Tomato Sauce', N'طبق خضار بصوص الطماطم', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-16711808', N'-16777216', 0, 0, 18, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:09:26', N'2018-07-12 17:18:40', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1403', N'Sauted Vegetables', N'خضار سوتيه', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-16711808', N'-16777216', 0, 0, 22, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:09:58', N'2018-07-12 17:18:56', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1404', N'Mixed Stuffed Vgetables	', N'محاشى الموسم', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-16711808', N'-16777216', 0, 0, 21, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:10:23', N'2018-07-12 17:19:09', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1405', N'Vine Leaves', N'ورق عنب', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-16711808', N'-16777216', 0, 0, 19, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:10:49', N'2018-07-12 17:19:19', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1501', N'Moloukhya', N'ملوخية', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 22, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:12:32', N'2019-07-05 19:15:19', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1502', N'Mesakaa Plain', N'مسقعة سادة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 29, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:12:53', N'2019-07-05 19:15:28', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1503', N'Mesakaa With Meat', N'مسقعة بالحمة', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 24, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:13:12', N'2019-10-01 13:08:01', 8, 0, 0, 1, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1504', N'Stuffed Sausge', N'طبق ممبار', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 33, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:13:32', N'2019-07-05 19:15:42', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1505', N'Hawawshi', N'حوواشى', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 38, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:13:53', N'2019-07-05 19:15:54', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)
INSERT INTO [dbo].[EldahanItems2] ([Code], [Name], [Name2], [BarCode], [CrossCode], [Taxable], [Assimbly], [EldahanPresetId], [IsModifier], [StandAlone], [PrintOnChick], [PrintOnReport], [FollowItem], [Image_Item], [BackColor], [fontColor], [Cost], [OpenPrice], [StaticPrice], [Description1], [Description2], [Description3], [Description4], [ModPrice_0], [ItemFont], [UseItemTimer], [ItemTimerValue], [Active], [CreateDate], [ModifiedDate], [User_ID], [NoServiceCharge], [Market_Price], [Item_Track], [PrintItemOnCheck], [IsParent], [Rest_ID_Active], [Open_Food], [Mod_Price], [Pre_Paid_Card]) VALUES (N'1506', N'AlexandrianLiver	', N'كبده اسكندرانى', N'', 0, 1, 0, 6, 0, 0, 0, 0, 0, NULL, N'-8323073', N'-16777216', 0, 0, 39, N'', N'', N'', N'', 0, N'Arial, 10pt, style=Bold', 0, 0, 1, N'2018-01-13 16:14:13', N'2019-07-05 19:16:01', 3, 0, 0, 0, 1, 0, 1, 0, 0, 0)

");
        }
        
        public override void Down()
        {
        }
    }
}
